/dts-v1/;
#include <behaviors.dtsi>
#include <bindings/zmk,pointing.dtsi>
#include <bindings/zmk,outputs.dtsi>

/ {
    chosen {
        zmk,pointing = &cirque_pinnacle;
    };
};

&i2c0 {
    status = "okay";
    cirque_pinnacle: cirque_pinnacle@2b {
        compatible = "zmk,pointing-cirque-pinnacle-i2c";
        reg = <0x2b>;
        label = "CIRQUE_PINNACLE";
        irq-gpios = <&gpio0 29 GPIO_ACTIVE_LOW>;
        pinctrl-0 = <&i2c0_default>;
        pinctrl-names = "default";
    };
};
