manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: cirque
      url-base: https://github.com/behreajj

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    - name: GammaKinematics
      url-base: https://github.com/GammaKinematics
      revision: main

  self:
    path: config
