manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: gammakinematics
      url-base: https://github.com/GammaKinematics

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    - name: zmk-driver-trackpad
      remote: gammakinematics
      revision: main

  self:
    path: conf ig
