manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: gammakinematics
      url-base: https://github.com/gammakinematics

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml

    - name: zmk-cirque-pinnacle
      remote: gammakinematics
      revision: main

  self:
    path: config
